import React from 'react';
import { Container } from '../Container';
import styles from './PrivacyPolicyPage.module.scss';
import heroTexture from '../../assets/about/about-hero-texture.webp?url';
import heroGlow from '../../assets/about/about-hero-glow.webp?url';

const introParagraphs = [
  'This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.',
  'We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.',
];

const definitionItems = [
  'Account means a unique account created for You to access our Service or parts of our Service.',
  'Affiliate means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.',
  'Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to BRIGHTRIVER ANALYTICS PTE. LTD., 1 George Street, #10-01, Singapore 049145.',
  'Cookies are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.',
  'Cookies are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.',
  'Country refers to: Singapore',
  'Device means any device that can access the Service such as a computer, a cellphone or a digital tablet.',
  'Personal Data is any information that relates to an identified or identifiable individual.',
  'Service refers to the Website.',
  'Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).',
  'Website refers to brightriver.ai, accessible from https://brightriver.ai',
  'You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.',
];

const personalDataItems = ['Email address', 'First name and last name', 'Phone Number', 'Usage Data'];

const cookieItems = [
  'Cookies or Browser Cookies. A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.',
  'Web Beacons. Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).',
];

const cookiePurposes = [
  {
    title: 'Necessary / Essential Cookies',
    detailLines: [
      'Type: Session Cookies',
      'Administered by: Us',
      'Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.',
    ],
  },
  {
    title: 'Cookies Policy / Notice Acceptance Cookies',
    detailLines: [
      'Type: Persistent Cookies',
      'Administered by: Us',
      'Purpose: These Cookies identify if users have accepted the use of cookies on the Website.',
    ],
  },
  {
    title: 'Functionality Cookies',
    detailLines: [
      'Type: Persistent Cookies',
      'Administered by: Us',
      'Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.',
    ],
  },
];

const useOfPersonalDataItems = [
  'To provide and maintain our Service, including to monitor the usage of our Service.',
  'To manage Your Account: to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.',
  'For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.',
  "To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.",
  'To provide You with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.',
  'To manage Your requests: To attend and manage Your requests to Us.',
  'For business transfers: We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.',
];

const shareItems = [
  'With Service Providers: We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to contact You.',
  'For business transfers: We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.',
  'With Affiliates: We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.',
  'With business partners: We may share Your information with Our business partners to offer You certain products, services or promotions.',
  'With other users: when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside.',
  'With Your consent: We may disclose Your personal information for any other purpose with Your consent.',
];

const legalRequirementItems = [
  'Comply with a legal obligation',
  'Protect and defend the rights or property of the Company',
  'Prevent or investigate possible wrongdoing in connection with the Service',
  'Protect the personal safety of Users of the Service or the public',
  'Protect against legal liability',
];

function BulletList({ items, className = '' }) {
  return (
    <ul className={`${styles.bulletList} ${className}`.trim()}>
      {items.map((item) => (
        <li key={item}>{item}</li>
      ))}
    </ul>
  );
}

function PolicyParagraphs({ paragraphs }) {
  return (
    <div className={styles.paragraphGroup}>
      {paragraphs.map((paragraph, index) => (
        <p key={index}>{paragraph}</p>
      ))}
    </div>
  );
}

export function PrivacyPolicyPage() {
  return (
    <>
      <main>
        <section className={styles.hero} aria-labelledby="privacy-policy-title">
        <div className={styles.backdrop} aria-hidden="true">
          <div className={styles.baseGradient} />
          <div className={styles.textureWrap}>
            <img src={heroTexture} alt="" />
          </div>
          <img className={styles.glow} src={heroGlow} alt="" />
        </div>

        <Container>
          <div className={styles.heroInner}>
            <h1 id="privacy-policy-title" data-reveal style={{ '--reveal-delay': '0.2s' }}>
              Privacy Policy
            </h1>
            <p className={styles.heroDate} data-reveal style={{ '--reveal-delay': '0.3s' }}>
              Last updated: February 10, 2025
            </p>
            <div className={styles.heroSummary} data-reveal style={{ '--reveal-delay': '0.4s' }}>
              {introParagraphs.map((paragraph) => (
                <p key={paragraph}>{paragraph}</p>
              ))}
            </div>
          </div>
        </Container>
      </section>

      <section className={styles.policySection} aria-labelledby="privacy-policy-content-title">
        <Container>
          <div className={styles.policyCard} data-reveal>
            <h2 id="privacy-policy-content-title" className={styles.policyTitle} data-reveal>
              Privacy Policy
            </h2>

            <div className={styles.policyBlock} data-reveal>
              <h3>Interpretation and Definitions</h3>

              <div className={styles.subBlock}>
                <h4>Interpretation</h4>
                <p>
                  The words of which the initial letter is capitalized have meanings defined
                  under the following conditions. The following definitions shall have the same
                  meaning regardless of whether they appear in singular or in plural.
                </p>
              </div>

              <div className={styles.subBlock}>
                <h4>Definitions</h4>
                <p>For the purposes of this Privacy Policy:</p>
                <BulletList items={definitionItems} />
              </div>
            </div>

            <div className={styles.policyBlock} data-reveal>
              <h3>Collecting and Using Your Personal Data</h3>

              <div className={styles.subBlock}>
                <h4>Type of Data Collected</h4>

                <div className={styles.subBlock}>
                  <h5>Personal Data</h5>
                  <p>
                    While using Our Service, We may ask You to provide Us with certain personally
                    identifiable information that can be used to contact or identify You.
                    Personally identifiable information may include, but is not limited to:
                  </p>
                  <BulletList items={personalDataItems} />
                </div>

                <div className={styles.subBlock}>
                  <h5>Usage Data</h5>
                  <PolicyParagraphs
                    paragraphs={[
                      'Usage Data is collected automatically when using the Service.',
                      "Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.",
                      'When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.',
                      'We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.',
                    ]}
                  />
                </div>

                <div className={styles.subBlock}>
                  <h5>Tracking Technologies and Cookies</h5>
                  <PolicyParagraphs
                    paragraphs={[
                      'We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:',
                    ]}
                  />
                  <BulletList items={cookieItems} />
                  <PolicyParagraphs
                    paragraphs={[
                      <>
                        Cookies can be &quot;Persistent&quot; or &quot;Session&quot; Cookies. Persistent
                        Cookies remain on Your personal computer or mobile device when You go
                        offline, while Session Cookies are deleted as soon as You close Your web
                        browser. You can learn more about cookies on{' '}
                        <a
                          href="https://www.termsfeed.com/blog/cookies/#What_Are_Cookies"
                          target="_blank"
                          rel="noopener noreferrer"
                          className={styles.inlineLink}
                        >
                          TermsFeed website
                        </a>{' '}
                        article.
                      </>,
                      'We use both Session and Persistent Cookies for the purposes set out below:',
                    ]}
                  />

                  <div className={styles.cookieGroups}>
                    {cookiePurposes.map((group) => (
                      <div className={styles.cookieGroup} key={group.title}>
                        <p className={styles.listHeading}>{group.title}</p>
                        <div className={styles.detailGroup}>
                          {group.detailLines.map((line) => (
                            <p key={line}>{line}</p>
                          ))}
                        </div>
                      </div>
                    ))}
                  </div>

                  <p>
                    For more information about the cookies we use and your choices regarding
                    cookies, please visit our Cookies Policy or the Cookies section of our
                    Privacy Policy.
                  </p>
                </div>
              </div>
            </div>

            <div className={styles.policyBlock} data-reveal>
              <h4>Use of Your Personal Data</h4>
              <p>The Company may use Personal Data for the following purposes:</p>
              <BulletList items={useOfPersonalDataItems} />
              <p>We may share Your personal information in the following situations:</p>
              <BulletList items={shareItems} />
            </div>

            <div className={styles.policyBlock} data-reveal>
              <h4>Retention of Your Personal Data</h4>
              <PolicyParagraphs
                paragraphs={[
                  'The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.',
                  'The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.',
                ]}
              />
            </div>

            <div className={styles.policyBlock} data-reveal>
              <h4>Transfer of Your Personal Data</h4>
              <PolicyParagraphs
                paragraphs={[
                  "Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to and maintained on computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.",
                  'Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.',
                  'The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.',
                ]}
              />
            </div>

            <div className={styles.policyBlock} data-reveal>
              <h4>Delete Your Personal Data</h4>
              <PolicyParagraphs
                paragraphs={[
                  'You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.',
                  'Our Service may give You the ability to delete certain information about You from within the Service.',
                  'You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting the account settings section that allows you to manage Your personal information. You may also contact Us to request access to, correct, or delete any personal information that You have provided to Us.',
                  'Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.',
                ]}
              />
            </div>

            <div className={styles.policyBlock} data-reveal>
              <h4>Disclosure of Your Personal Data</h4>

              <div className={styles.subBlock}>
                <h5>Business Transactions</h5>
                <p>
                  If the Company is involved in a merger, acquisition or asset sale, Your
                  Personal Data may be transferred. We will provide notice before Your Personal
                  Data is transferred and becomes subject to a different Privacy Policy.
                </p>
              </div>

              <div className={styles.subBlock}>
                <h5>Law enforcement</h5>
                <p>
                  Under certain circumstances, the Company may be required to disclose Your
                  Personal Data if required to do so by law or in response to valid requests by
                  public authorities (e.g. a court or a government agency).
                </p>
              </div>

              <div className={styles.subBlock}>
                <h5>Other legal requirements</h5>
                <p>
                  The Company may disclose Your Personal Data in the good faith belief that such
                  action is necessary to:
                </p>
                <BulletList items={legalRequirementItems} />
              </div>
            </div>

            <div className={styles.policyBlock} data-reveal>
              <h4>Security of Your Personal Data</h4>
              <p>
                The security of Your Personal Data is important to Us, but remember that no
                method of transmission over the Internet, or method of electronic storage is 100%
                secure. While We strive to use commercially acceptable means to protect Your
                Personal Data, We cannot guarantee its absolute security.
              </p>
            </div>

            <div className={styles.policyBlock} data-reveal>
              <h4>Children&apos;s Privacy</h4>
              <PolicyParagraphs
                paragraphs={[
                  'Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.',
                  "If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.",
                ]}
              />
            </div>

            <div className={styles.policyBlock} data-reveal>
              <h4>Links to Other Websites</h4>
              <PolicyParagraphs
                paragraphs={[
                  'Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party site. We strongly advise You to review the Privacy Policy of every site You visit.',
                  'We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.',
                ]}
              />
            </div>

            <div className={styles.policyBlock} data-reveal>
              <h4>Changes to this Privacy Policy</h4>
              <PolicyParagraphs
                paragraphs={[
                  'We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.',
                  'We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.',
                  'You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.',
                ]}
              />
            </div>

            <div className={styles.policyBlock} data-reveal>
              <h4>Contact Us</h4>
              <p>
                If you have any questions regarding this Privacy Policy, please contact us{' '}
                <a href="/contact" className={styles.inlineLink}>
                  here
                </a>
                .
              </p>
            </div>
          </div>
        </Container>
      </section>
    </main>
    </>
  );
}
